# Site settings
title: Code Over Stack
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Basics settings
# url: "http://localhost:4000" # the base hostname & protocol
baseurl: ""
baseassets: "assets/images/"

# Socials
email: contact@codeoverstack.io
twitter_username: codeoverstack
github_username:  jekyll

# Pagination settings
paginate: 40
paginate_path: "/page/:num"

# Build settings
markdown: kramdown
exclude: [OLD]

# Jekyll libs
gems:
  - jekyll-paginate
  - jekyll-gist

# Comments on articles
comments: true
disqus_shortname: ingloriouscoders
